### ISSUE TITLE
runtests doesn't complete

### ISSUE THREAD

**Issue by neurotensin** [OpenMendel/TrajGWAS.jl#29]
The tests do not complete with julia 1.4.1 , 1.5 or 1.7.2. 

Included is the error trace for julia-1.7.2-linux-x86_64.tar.gz
[trajgwas-runtest-errors-julia-1.7.2.txt](https://github.com/OpenMendel/TrajGWAS.jl/files/8481649/trajgwas-runtest-errors-julia-1.7.2.txt)

Is this a regression?

**Comment by neurotensin** [comment]
an undocumented feature is that julia needs to be run with "--project" to instantiate the specific configuration to run the tests. 
A makefile that implemented this , would be good for new users.

**Comment by kose-y** [comment]
Thanks for the report. I do see tests that are not running as expected with some of the dependencies updated, so reopening the issue.

**Comment by kose-y** [comment]
Seems to be an issue from upstream packages. This issue has now been resolved.
