### ISSUE TITLE
Cannot compute Wald test with no within-subject covariates

### ISSUE THREAD

**Issue by Pintaius** [OpenMendel/TrajGWAS.jl#30]
Hello,
I am trying to run a model with covariates only on the _mean effects_ formula. This runs perfectly and very quickly using the default (score) test, but I am getting the following error when I switch to Wald:

> MethodError: no method matching iterate(::ConstantTerm{Int64})

After some back-and-forth, I managed to trace this back to having no covariates on the _within-subject variance effects_ formula, and do indeed get the same error with the example dataset if I run:

`trajgwas(@formula(y ~ 1 + sex + onMeds),
               @formula(y ~ 1),
               @formula(y ~ 1),
               :id,
               datadir * "trajgwas_plinkex.csv",
               datadir * "hapmap3",
               pvalfile = "wald.pval.txt",
               snpinds = 1:5,
               test = :wald)`

Is this intentional or could it be addressed? I would like to obtain effect sizes for my intended model without having to re-run SNP associations in a different software.

Thank you for any help!

**Comment by kose-y** [comment]
We also have a similar issue with another GWAS package in our group. We will make this possible soon. Sorry for the late reply.

**Comment by SimonWiegrebe** [comment]
Hi, I (still) ran into the same problem today, using your example dataset. Will this issue be fixed soon?

**Comment by kose-y** [comment]
Fixed on the main branch. A new version will be tagged along with the fix for #33.
