### ISSUE TITLE
Change the link function

### ISSUE THREAD

**Issue by naaziz10** [OpenMendel/TrajGWAS.jl#42]
Hi,

According to the TrajGWAS documentation it should be possible to change the link function, by setting the link flag, i.e.:

"link::GLM.Link: LogitLink() (default), ProbitLink(), CauchitLink(), or CloglogLink()."

However, when I try to set 'link=CloglogLink()' within the trajgwas() function, I get the following error message:

_got unsupported keyword argument "link"_

So my question is: how can one set the link keyword correctly in the trajgwas() function?

Thanks!

**Comment by kose-y** [comment]
Hi, 

Oops, it seems that line was accidentally left in after being copied from another GWAS package we developed. This package does not support the link function. I will remove that information from the docstring.

**Comment by naaziz10** [comment]
OK, thanks for the clarification.
